GET http://localhost:8000/user

###

POST  http://localhost:8000/user
Content-Type: application/json

{
    "name": "Omkar Paschapur",
    "email": "00015omkar@gmail.com",
    "image": "https://img.clerk.com/eyJ0eXBlIjoicHJveHkiLCJzcmMiOiJodHRwczovL2ltYWdlcy5jbGVyay5kZXYvb2F1dGhfZ29vZ2xlL2ltZ18zMDhSZnYxUXRyc0x1ajUxclJWQVlVcUJSdHMifQ"
}

###
GET http://localhost:8000/post

###
POST http://localhost:8000/post
Content-Type: application/json

{
    "postText": "Sample Post Message",
    "createdAt": "343431",
    "createdBy": "68848d937928a391103babdc",
    "imageUrl": "Sample-url"
}

###
GET http://localhost:8000/user/00015omkar@gmail.com